spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver

  redis:
    host: localhost
    port: 6379
    timeout: 6000

logging:
  level:
    root: DEBUG

app:
  domain: "http://localhost:8080"