spring:
  application:
    name: url-shortener

  profiles:
    active: dev # Default profile

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8080

app:
  domain: "http://localhost:8080"
